/** Audit event catalog (spec §39). Every mutation of business-critical
 * state must write one of these through the AuditLog service — never
 * insert raw strings so the set stays enumerable and queryable. */
export enum AuditAction {
  USER_SIGNED_UP = "USER_SIGNED_UP",
  USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  USER_SUSPENDED = "USER_SUSPENDED",

  CAMPAIGN_CREATED = "CAMPAIGN_CREATED",
  CAMPAIGN_EDITED = "CAMPAIGN_EDITED",
  CAMPAIGN_SUBMITTED = "CAMPAIGN_SUBMITTED",
  CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED",
  CAMPAIGN_REJECTED = "CAMPAIGN_REJECTED",
  CAMPAIGN_CANCELLED = "CAMPAIGN_CANCELLED",

  PAYMENT_INITIATED = "PAYMENT_INITIATED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  FUNDS_RESERVED = "FUNDS_RESERVED",

  CREATOR_MATCHED = "CREATOR_MATCHED",
  OFFER_SENT = "OFFER_SENT",
  OFFER_VIEWED = "OFFER_VIEWED",
  OFFER_ACCEPTED = "OFFER_ACCEPTED",
  OFFER_REJECTED = "OFFER_REJECTED",
  OFFER_EXPIRED = "OFFER_EXPIRED",

  AGREEMENT_GENERATED = "AGREEMENT_GENERATED",
  AGREEMENT_ACCEPTED = "AGREEMENT_ACCEPTED",

  ADDRESS_SUBMITTED = "ADDRESS_SUBMITTED",
  SHIPMENT_CREATED = "SHIPMENT_CREATED",
  SHIPMENT_SHIPPED = "SHIPMENT_SHIPPED",
  SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED",
  PRODUCT_RECEIVED = "PRODUCT_RECEIVED",

  CONTENT_SUBMITTED = "CONTENT_SUBMITTED",
  REVISION_REQUESTED = "REVISION_REQUESTED",
  CONTENT_APPROVED = "CONTENT_APPROVED",

  VERIFICATION_PASSED = "VERIFICATION_PASSED",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  RETENTION_PASSED = "RETENTION_PASSED",
  RETENTION_FAILED = "RETENTION_FAILED",

  PAYOUT_RELEASED = "PAYOUT_RELEASED",
  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED",
  WITHDRAWAL_PAID = "WITHDRAWAL_PAID",
  WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED",
  REFUND_CREATED = "REFUND_CREATED",

  KYC_SUBMITTED = "KYC_SUBMITTED",
  KYC_APPROVED = "KYC_APPROVED",
  KYC_REJECTED = "KYC_REJECTED",

  DISPUTE_OPENED = "DISPUTE_OPENED",
  DISPUTE_DECISION = "DISPUTE_DECISION",
  DISPUTE_RESOLVED = "DISPUTE_RESOLVED",

  ADMIN_DECISION = "ADMIN_DECISION",
  FRAUD_FLAG_RAISED = "FRAUD_FLAG_RAISED",
  FRAUD_FLAG_CLEARED = "FRAUD_FLAG_CLEARED",
}

export interface AuditEntry {
  actorId: string | null;
  actorRole: string | null;
  action: AuditAction;
  entityType: string;
  entityId: string;
  oldValue?: unknown;
  newValue?: unknown;
  metadata?: Record<string, unknown>;
}
